# Generated by Django 5.1.4 on 2025-02-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyyyy', '0002_articals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='articals',
        ),
    ]
