# Generated by Django 5.1.4 on 2025-02-01 16:49

import shopifyyyy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyyyy', '0003_delete_articals'),
    ]

    operations = [
        migrations.CreateModel(
            name='articals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to=shopifyyyy.models.getFileName)),
                ('blog_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
