# Generated by Django 5.1.4 on 2025-02-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyyyy', '0004_articals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=200),
        ),
    ]
