# Generated by Django 5.1.4 on 2025-02-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyyyy', '0007_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='product_quantity',
        ),
    ]
