# Generated by Django 5.1.4 on 2025-02-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyyyy', '0008_rename_quantity_cart_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='User',
        ),
    ]
