# Generated by Django 5.1.4 on 2025-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyyyy', '0010_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='final_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
